--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2026. 01. 23. 10:18:17
-- Server version: 5.7.44
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS computerwebshop;

CREATE DATABASE IF NOT EXISTS computerwebshop
	CHARACTER SET latin1
	COLLATE latin1_swedish_ci;

--
-- Set default database
--
USE computerwebshop;

--
-- Create table `units`
--
CREATE TABLE IF NOT EXISTS units (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  unit_name VARCHAR(15) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 45,
AVG_ROW_LENGTH = 372,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `units_unit_name_unique` on table `units`
--
ALTER TABLE units 
  ADD UNIQUE INDEX units_unit_name_unique(unit_name);

--
-- Create table `companies`
--
CREATE TABLE IF NOT EXISTS companies (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  company_name VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 26,
AVG_ROW_LENGTH = 655,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `companies_company_name_unique` on table `companies`
--
ALTER TABLE companies 
  ADD UNIQUE INDEX companies_company_name_unique(company_name);

--
-- Create table `categories`
--
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  category_name VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 21,
AVG_ROW_LENGTH = 819,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `categories_category_name_unique` on table `categories`
--
ALTER TABLE categories 
  ADD UNIQUE INDEX categories_category_name_unique(category_name);

--
-- Create table `products`
--
CREATE TABLE IF NOT EXISTS products (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  category_id BIGINT(20) UNSIGNED NOT NULL,
  name VARCHAR(150) NOT NULL,
  pcs INT(11) NOT NULL,
  price DECIMAL(15, 2) NOT NULL,
  description TEXT NOT NULL,
  company_id BIGINT(20) UNSIGNED NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE products 
  ADD CONSTRAINT products_category_id_foreign FOREIGN KEY (category_id)
    REFERENCES categories(id);

--
-- Create foreign key
--
ALTER TABLE products 
  ADD CONSTRAINT products_company_id_foreign FOREIGN KEY (company_id)
    REFERENCES companies(id);

--
-- Create table `pics`
--
CREATE TABLE IF NOT EXISTS pics (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id BIGINT(20) UNSIGNED NOT NULL,
  image_path VARCHAR(150) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE pics 
  ADD CONSTRAINT pics_product_id_foreign FOREIGN KEY (product_id)
    REFERENCES products(id) ON DELETE CASCADE;

--
-- Create table `parameters`
--
CREATE TABLE IF NOT EXISTS parameters (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  parameter_name VARCHAR(50) NOT NULL,
  category_id BIGINT(20) UNSIGNED NOT NULL,
  unit_id BIGINT(20) UNSIGNED NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 34,
AVG_ROW_LENGTH = 496,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `parameters_parameter_name_unique` on table `parameters`
--
ALTER TABLE parameters 
  ADD UNIQUE INDEX parameters_parameter_name_unique(parameter_name);

--
-- Create foreign key
--
ALTER TABLE parameters 
  ADD CONSTRAINT parameters_category_id_foreign FOREIGN KEY (category_id)
    REFERENCES categories(id);

--
-- Create foreign key
--
ALTER TABLE parameters 
  ADD CONSTRAINT parameters_unit_id_foreign FOREIGN KEY (unit_id)
    REFERENCES units(id);

--
-- Create table `product_parameter`
--
CREATE TABLE IF NOT EXISTS product_parameter (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id BIGINT(20) UNSIGNED NOT NULL,
  parameter_id BIGINT(20) UNSIGNED NOT NULL,
  value VARCHAR(191) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE product_parameter 
  ADD CONSTRAINT product_parameter_parameter_id_foreign FOREIGN KEY (parameter_id)
    REFERENCES parameters(id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE product_parameter 
  ADD CONSTRAINT product_parameter_product_id_foreign FOREIGN KEY (product_id)
    REFERENCES products(id) ON DELETE CASCADE;

--
-- Create table `users`
--
CREATE TABLE IF NOT EXISTS users (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(191) NOT NULL,
  email VARCHAR(191) NOT NULL,
  email_verified_at TIMESTAMP NULL DEFAULT NULL,
  password VARCHAR(191) NOT NULL,
  role INT(11) NOT NULL,
  phone VARCHAR(191) NOT NULL,
  city VARCHAR(191) NOT NULL,
  street VARCHAR(191) NOT NULL,
  house_number VARCHAR(191) NOT NULL,
  zip_code VARCHAR(191) NOT NULL,
  billing_phone VARCHAR(191) DEFAULT NULL,
  billing_city VARCHAR(191) DEFAULT NULL,
  billing_street VARCHAR(191) DEFAULT NULL,
  billing_house_number VARCHAR(191) DEFAULT NULL,
  billing_zip_code VARCHAR(191) DEFAULT NULL,
  remember_token VARCHAR(100) DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 12,
AVG_ROW_LENGTH = 1489,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `users_email_unique` on table `users`
--
ALTER TABLE users 
  ADD UNIQUE INDEX users_email_unique(email);

--
-- Create table `comments`
--
CREATE TABLE IF NOT EXISTS comments (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT(20) UNSIGNED NOT NULL,
  product_id BIGINT(20) UNSIGNED NOT NULL,
  comment TEXT NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `comments_user_id_product_id_unique` on table `comments`
--
ALTER TABLE comments 
  ADD UNIQUE INDEX comments_user_id_product_id_unique(user_id, product_id);

--
-- Create foreign key
--
ALTER TABLE comments 
  ADD CONSTRAINT comments_product_id_foreign FOREIGN KEY (product_id)
    REFERENCES products(id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE comments 
  ADD CONSTRAINT comments_user_id_foreign FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE CASCADE;

--
-- Create table `carts`
--
CREATE TABLE IF NOT EXISTS carts (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT(20) UNSIGNED NOT NULL,
  date DATE NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE carts 
  ADD CONSTRAINT carts_user_id_foreign FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE CASCADE;

--
-- Create table `cart_items`
--
CREATE TABLE IF NOT EXISTS cart_items (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  cart_id BIGINT(20) UNSIGNED NOT NULL,
  product_id BIGINT(20) UNSIGNED NOT NULL,
  pcs INT(11) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `cart_items_cart_id_product_id_unique` on table `cart_items`
--
ALTER TABLE cart_items 
  ADD UNIQUE INDEX cart_items_cart_id_product_id_unique(cart_id, product_id);

--
-- Create foreign key
--
ALTER TABLE cart_items 
  ADD CONSTRAINT cart_items_cart_id_foreign FOREIGN KEY (cart_id)
    REFERENCES carts(id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE cart_items 
  ADD CONSTRAINT cart_items_product_id_foreign FOREIGN KEY (product_id)
    REFERENCES products(id) ON DELETE CASCADE;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;