--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2026. 01. 20. 8:14:32
-- Server version: 5.7.44
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS computerwebshop;

CREATE DATABASE IF NOT EXISTS computerwebshop
	CHARACTER SET latin1
	COLLATE latin1_swedish_ci;

--
-- Set default database
--
USE computerwebshop;

--
-- Create table `units`
--
CREATE TABLE IF NOT EXISTS units (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  unit_name VARCHAR(15) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `units_unit_name_unique` on table `units`
--
ALTER TABLE units 
  ADD UNIQUE INDEX units_unit_name_unique(unit_name);

--
-- Create table `companies`
--
CREATE TABLE IF NOT EXISTS companies (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  company_name VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `companies_company_name_unique` on table `companies`
--
ALTER TABLE companies 
  ADD UNIQUE INDEX companies_company_name_unique(company_name);

--
-- Create table `categories`
--
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  category_name VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `categories_category_name_unique` on table `categories`
--
ALTER TABLE categories 
  ADD UNIQUE INDEX categories_category_name_unique(category_name);

--
-- Create table `products`
--
CREATE TABLE IF NOT EXISTS products (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  category_id BIGINT(20) UNSIGNED NOT NULL,
  name VARCHAR(150) NOT NULL,
  pcs INT(11) NOT NULL,
  price DECIMAL(15, 2) NOT NULL,
  description TEXT NOT NULL,
  company_id BIGINT(20) UNSIGNED NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE products 
  ADD CONSTRAINT products_category_id_foreign FOREIGN KEY (category_id)
    REFERENCES categories(id);

--
-- Create foreign key
--
ALTER TABLE products 
  ADD CONSTRAINT products_company_id_foreign FOREIGN KEY (company_id)
    REFERENCES companies(id);

--
-- Create table `pics`
--
CREATE TABLE IF NOT EXISTS pics (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id BIGINT(20) UNSIGNED NOT NULL,
  image_path VARCHAR(150) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE pics 
  ADD CONSTRAINT pics_product_id_foreign FOREIGN KEY (product_id)
    REFERENCES products(id) ON DELETE CASCADE;

--
-- Create table `parameters`
--
CREATE TABLE IF NOT EXISTS parameters (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  parameter_name VARCHAR(50) NOT NULL,
  category_id BIGINT(20) UNSIGNED NOT NULL,
  unit_id BIGINT(20) UNSIGNED NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `parameters_parameter_name_unique` on table `parameters`
--
ALTER TABLE parameters 
  ADD UNIQUE INDEX parameters_parameter_name_unique(parameter_name);

--
-- Create foreign key
--
ALTER TABLE parameters 
  ADD CONSTRAINT parameters_category_id_foreign FOREIGN KEY (category_id)
    REFERENCES categories(id);

--
-- Create foreign key
--
ALTER TABLE parameters 
  ADD CONSTRAINT parameters_unit_id_foreign FOREIGN KEY (unit_id)
    REFERENCES units(id);

--
-- Create table `product_parameters`
--
CREATE TABLE IF NOT EXISTS product_parameters (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  parameter_id BIGINT(20) UNSIGNED NOT NULL,
  product_id BIGINT(20) UNSIGNED NOT NULL,
  value VARCHAR(191) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `product_parameters_parameter_id_product_id_unique` on table `product_parameters`
--
ALTER TABLE product_parameters 
  ADD UNIQUE INDEX product_parameters_parameter_id_product_id_unique(parameter_id, product_id);

--
-- Create foreign key
--
ALTER TABLE product_parameters 
  ADD CONSTRAINT product_parameters_parameter_id_foreign FOREIGN KEY (parameter_id)
    REFERENCES parameters(id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE product_parameters 
  ADD CONSTRAINT product_parameters_product_id_foreign FOREIGN KEY (product_id)
    REFERENCES products(id) ON DELETE CASCADE;

--
-- Create table `users`
--
CREATE TABLE IF NOT EXISTS users (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(191) NOT NULL,
  email VARCHAR(191) NOT NULL,
  email_verified_at TIMESTAMP NULL DEFAULT NULL,
  password VARCHAR(191) NOT NULL,
  role INT(11) NOT NULL,
  phone VARCHAR(191) NOT NULL,
  city VARCHAR(191) NOT NULL,
  street VARCHAR(191) NOT NULL,
  house_number VARCHAR(191) NOT NULL,
  zip_code VARCHAR(191) NOT NULL,
  billing_phone VARCHAR(191) DEFAULT NULL,
  billing_city VARCHAR(191) DEFAULT NULL,
  billing_street VARCHAR(191) DEFAULT NULL,
  billing_house_number VARCHAR(191) DEFAULT NULL,
  billing_zip_code VARCHAR(191) DEFAULT NULL,
  remember_token VARCHAR(100) DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `users_email_unique` on table `users`
--
ALTER TABLE users 
  ADD UNIQUE INDEX users_email_unique(email);

--
-- Create table `comments`
--
CREATE TABLE IF NOT EXISTS comments (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT(20) UNSIGNED NOT NULL,
  product_id BIGINT(20) UNSIGNED NOT NULL,
  comment TEXT NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `comments_user_id_product_id_unique` on table `comments`
--
ALTER TABLE comments 
  ADD UNIQUE INDEX comments_user_id_product_id_unique(user_id, product_id);

--
-- Create foreign key
--
ALTER TABLE comments 
  ADD CONSTRAINT comments_product_id_foreign FOREIGN KEY (product_id)
    REFERENCES products(id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE comments 
  ADD CONSTRAINT comments_user_id_foreign FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE CASCADE;

--
-- Create table `carts`
--
CREATE TABLE IF NOT EXISTS carts (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT(20) UNSIGNED NOT NULL,
  date DATE NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE carts 
  ADD CONSTRAINT carts_user_id_foreign FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE CASCADE;

--
-- Create table `cart_items`
--
CREATE TABLE IF NOT EXISTS cart_items (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  cart_id BIGINT(20) UNSIGNED NOT NULL,
  product_id BIGINT(20) UNSIGNED NOT NULL,
  pcs INT(11) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `cart_items_cart_id_product_id_unique` on table `cart_items`
--
ALTER TABLE cart_items 
  ADD UNIQUE INDEX cart_items_cart_id_product_id_unique(cart_id, product_id);

--
-- Create foreign key
--
ALTER TABLE cart_items 
  ADD CONSTRAINT cart_items_cart_id_foreign FOREIGN KEY (cart_id)
    REFERENCES carts(id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE cart_items 
  ADD CONSTRAINT cart_items_product_id_foreign FOREIGN KEY (product_id)
    REFERENCES products(id) ON DELETE CASCADE;

--
-- Create table `sessions`
--
CREATE TABLE IF NOT EXISTS sessions (
  id VARCHAR(191) NOT NULL,
  user_id BIGINT(20) UNSIGNED DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  user_agent TEXT DEFAULT NULL,
  payload LONGTEXT NOT NULL,
  last_activity INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `sessions_last_activity_index` on table `sessions`
--
ALTER TABLE sessions 
  ADD INDEX sessions_last_activity_index(last_activity);

--
-- Create index `sessions_user_id_index` on table `sessions`
--
ALTER TABLE sessions 
  ADD INDEX sessions_user_id_index(user_id);

--
-- Create table `personal_access_tokens`
--
CREATE TABLE IF NOT EXISTS personal_access_tokens (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  tokenable_type VARCHAR(191) NOT NULL,
  tokenable_id BIGINT(20) UNSIGNED NOT NULL,
  name TEXT NOT NULL,
  token VARCHAR(64) NOT NULL,
  abilities TEXT DEFAULT NULL,
  last_used_at TIMESTAMP NULL DEFAULT NULL,
  expires_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `personal_access_tokens_expires_at_index` on table `personal_access_tokens`
--
ALTER TABLE personal_access_tokens 
  ADD INDEX personal_access_tokens_expires_at_index(expires_at);

--
-- Create index `personal_access_tokens_token_unique` on table `personal_access_tokens`
--
ALTER TABLE personal_access_tokens 
  ADD UNIQUE INDEX personal_access_tokens_token_unique(token);

--
-- Create index `personal_access_tokens_tokenable_type_tokenable_id_index` on table `personal_access_tokens`
--
ALTER TABLE personal_access_tokens 
  ADD INDEX personal_access_tokens_tokenable_type_tokenable_id_index(tokenable_type, tokenable_id);

--
-- Create table `password_reset_tokens`
--
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  email VARCHAR(191) NOT NULL,
  token VARCHAR(191) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (email)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `migrations`
--
CREATE TABLE IF NOT EXISTS migrations (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  migration VARCHAR(191) NOT NULL,
  batch INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 16,
AVG_ROW_LENGTH = 1092,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `job_batches`
--
CREATE TABLE IF NOT EXISTS job_batches (
  id VARCHAR(191) NOT NULL,
  name VARCHAR(191) NOT NULL,
  total_jobs INT(11) NOT NULL,
  pending_jobs INT(11) NOT NULL,
  failed_jobs INT(11) NOT NULL,
  failed_job_ids LONGTEXT NOT NULL,
  options MEDIUMTEXT DEFAULT NULL,
  cancelled_at INT(11) DEFAULT NULL,
  created_at INT(11) NOT NULL,
  finished_at INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `jobs`
--
CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  queue VARCHAR(191) NOT NULL,
  payload LONGTEXT NOT NULL,
  attempts TINYINT(3) UNSIGNED NOT NULL,
  reserved_at INT(10) UNSIGNED DEFAULT NULL,
  available_at INT(10) UNSIGNED NOT NULL,
  created_at INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `jobs_queue_index` on table `jobs`
--
ALTER TABLE jobs 
  ADD INDEX jobs_queue_index(queue);

--
-- Create table `failed_jobs`
--
CREATE TABLE IF NOT EXISTS failed_jobs (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  uuid VARCHAR(191) NOT NULL,
  `connection` TEXT NOT NULL,
  queue TEXT NOT NULL,
  payload LONGTEXT NOT NULL,
  exception LONGTEXT NOT NULL,
  failed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `failed_jobs_uuid_unique` on table `failed_jobs`
--
ALTER TABLE failed_jobs 
  ADD UNIQUE INDEX failed_jobs_uuid_unique(uuid);

--
-- Create table `cache_locks`
--
CREATE TABLE IF NOT EXISTS cache_locks (
  `key` VARCHAR(191) NOT NULL,
  owner VARCHAR(191) NOT NULL,
  expiration INT(11) NOT NULL,
  PRIMARY KEY (`key`)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `cache`
--
CREATE TABLE IF NOT EXISTS cache (
  `key` VARCHAR(191) NOT NULL,
  value MEDIUMTEXT NOT NULL,
  expiration INT(11) NOT NULL,
  PRIMARY KEY (`key`)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

-- 
-- Dumping data for table units
--
-- Table computerwebshop.units does not contain any data (it is empty)

-- 
-- Dumping data for table companies
--
-- Table computerwebshop.companies does not contain any data (it is empty)

-- 
-- Dumping data for table categories
--
-- Table computerwebshop.categories does not contain any data (it is empty)

-- 
-- Dumping data for table parameters
--
-- Table computerwebshop.parameters does not contain any data (it is empty)

-- 
-- Dumping data for table users
--
-- Table computerwebshop.users does not contain any data (it is empty)

-- 
-- Dumping data for table products
--
-- Table computerwebshop.products does not contain any data (it is empty)

-- 
-- Dumping data for table carts
--
-- Table computerwebshop.carts does not contain any data (it is empty)

-- 
-- Dumping data for table sessions
--
-- Table computerwebshop.sessions does not contain any data (it is empty)

-- 
-- Dumping data for table product_parameters
--
-- Table computerwebshop.product_parameters does not contain any data (it is empty)

-- 
-- Dumping data for table pics
--
-- Table computerwebshop.pics does not contain any data (it is empty)

-- 
-- Dumping data for table personal_access_tokens
--
-- Table computerwebshop.personal_access_tokens does not contain any data (it is empty)

-- 
-- Dumping data for table password_reset_tokens
--
-- Table computerwebshop.password_reset_tokens does not contain any data (it is empty)

-- 
-- Dumping data for table migrations
--
INSERT INTO migrations VALUES
(1, '0001_01_01_000000_create_users_table', 1),
(2, '0001_01_01_000001_create_cache_table', 1),
(3, '0001_01_01_000002_create_jobs_table', 1),
(4, '2025_11_04_102115_create_personal_access_tokens_table', 1),
(5, '2026_01_16_082500_modify_users_table', 1),
(6, '2026_01_16_082511_create_companys_table', 1),
(7, '2026_01_16_082556_create_categories_table', 1),
(8, '2026_01_16_082625_create_units_table', 1),
(9, '2026_01_16_082632_create_parameters_table', 1),
(10, '2026_01_16_082639_create_products_table', 1),
(11, '2026_01_16_082643_create_carts_table', 1),
(12, '2026_01_16_082703_create_product_parameters_table', 1),
(13, '2026_01_16_083529_create_pics_table', 1),
(14, '2026_01_16_083533_create_comments_table', 1),
(15, '2026_01_16_083546_create_cart_items_table', 1);

-- 
-- Dumping data for table job_batches
--
-- Table computerwebshop.job_batches does not contain any data (it is empty)

-- 
-- Dumping data for table jobs
--
-- Table computerwebshop.jobs does not contain any data (it is empty)

-- 
-- Dumping data for table failed_jobs
--
-- Table computerwebshop.failed_jobs does not contain any data (it is empty)

-- 
-- Dumping data for table comments
--
-- Table computerwebshop.comments does not contain any data (it is empty)

-- 
-- Dumping data for table cart_items
--
-- Table computerwebshop.cart_items does not contain any data (it is empty)

-- 
-- Dumping data for table cache_locks
--
-- Table computerwebshop.cache_locks does not contain any data (it is empty)

-- 
-- Dumping data for table cache
--
-- Table computerwebshop.cache does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;