@baseUrl = http://localhost:8000/api


### ============================================
### NYILVÁNOS ENDPOINTS
### ============================================

### Teszt endpoint
GET {{baseUrl}}/x
### 1. Admin bejelentkezés
# @name login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123"
}
### token kiszed
@token = {{login.response.body.data.token}}

### logout user
POST  {{baseUrl}}/users/logout
Accept: application/json
Authorization: Bearer {{token}}

### 2. Vásárló bejelentkezés
# Előbb ezt futtatod, majd másold az "data.token" mezőt az @customerToken-hoz
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "vasarlo1@example.com",
  "password": "ronaldo"
}

### 3. Regisztráció (új felhasználó)
POST {{baseUrl}}/users
Content-Type: application/json
Accept: application/json

{
  "name": "Test User",
  "email": "testuser@example.com",
  "password": "password123",
  "phone": "06201234567",
  "city": "Budapest",
  "street": "Fő utca",
  "house_number": "10",
  "zip_code": "1011"
}

### --- companies
GET {{baseUrl}}/companies
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### --- categories
GET {{baseUrl}}/categories
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### --- units
GET {{baseUrl}}/units
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### --- products
GET {{baseUrl}}/products
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}
###- Post new product
POST {{baseUrl}}/products
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "name": "Kingston Fury Beast 16GB DDR5",
  "category_id": 1,
  "company_id": 1,
  "pcs": 10,
  "price": "32990.00",
  "description": "DDR5 RAM module"
}

### 

PATCH {{baseUrl}}/products/1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "price": "31990.00",
  "pcs": 15
}


### --- product_parameter
GET {{baseUrl}}/product_parameters
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### --- pics
GET {{baseUrl}}/pics
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### --- comments
GET {{baseUrl}}/comments
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


### --- comments
GET {{baseUrl}}/carts
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### --- cart items
GET {{baseUrl}}/carts
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}






