### Változók
@protocol = http://
@hostname = localhost
@port = 8000
@host = {{protocol}}{{hostname}}:{{port}}

### ============================================
### NYILVÁNOS ENDPOINTS
### ============================================

### --- user

### Teszt endpoint
GET {{host}}/api/x
### 1. Admin bejelentkezés
# @name login
POST {{host}}/api/users/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123"
}

### token kiszed
@token = {{login.response.body.data.token}}

### logout user
POST  {{host}}/api/users/logout
Accept: application/json
Authorization: Bearer {{token}}

### 2. Vásárló bejelentkezés
# Előbb ezt futtatod, majd másold az "data.token" mezőt az @customerToken-hoz
POST {{host}}/api/users/login
Content-Type: application/json

{
  "email": "vasarlo1@example.com",
  "password": "ronaldo"
}

### 3. Regisztráció (új felhasználó)
POST {{host}}/api/users
Content-Type: application/json
Accept: application/json

{
  "name": "Test User",
  "email": "testuser@example.com",
  "password": "password123",
  "phone": "06201234567",
  "city": "Budapest",
  "street": "Fő utca",
  "house_number": "10",
  "zip_code": "1011"
}

### --- categories
### get categies
GET {{host}}/api/categories
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### get categies by id
GET {{host}}/api/categories/21
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### post categoies
POST {{host}}/api/categories
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "category_name": "x"
}

### patch categoies
patch {{host}}/api/categories/20
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
    "category_name": "xx1"
}

### delete categoies
DELETE {{host}}/api/categories/21
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

